version: '3'
services:

  master:
    image: "ros:kinetic-ros-base"
    container_name: master
    command:
    - roscore

  control_node:
    build: control_node
    container_name: control
    depends_on:
    - "master"
    environment:
    - "ROS_HOSTNAME=control"
    - "ROS_MASTER_URI=http://master:11311"
    command: ./entrypoint.sh

  servo_node:
    build: servo_node
    container_name: servo
    depends_on:
    - "master"
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
    - "ROS_HOSTNAME=servo"
    - "ROS_MASTER_URI=http://master:11311"
    command: ./entrypoint.sh
